[general]
live_config_reload = true
working_directory = "None"

# Themes --
import = [ 
  "~/.config/alacritty/nordic.toml",
  "~/.config/alacritty/keybinds.toml"
]

[window]
title = "Alacritty"
decorations = "Full"
blur = true
opacity = 0.6
padding.x = 8
padding.y = 8
dynamic_title = true
dynamic_padding = true

[window.dimensions]
columns = 160
lines = 80

[cursor.style]
shape= "Beam"
blinking = "Always"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

#[env]
#TERM = "xterm-256color"

[font]
#glyph_offset = { x = 1, y = 0 }
normal.family = "FiraCode"
normal.style = "Regular"
size = 12.0

[font.bold]
family = "FiraCode"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"
