# Alacritty smooth config

window:
  padding:
    x: 8
    y: 8
  dynamic_padding: true
  decorations: full
  opacity: 0.95
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: FiraCode
    style: Regular
  bold:
    family: FiraCode
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic
  bold_italic:
    family: JetBrains Mono
    style: Bold Italic
  size: 12.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  builtin_box_drawing: true

cursor:
  style:
    shape: Beam
    blinking: Always
  blink_interval: 500
  unfocused_hollow: true

live_config_reload: true

colors:
  primary:
    background: '0x1e1e2e'
    foreground: '0xd9e0ee'
  cursor:
    text: '0x1e1e2e'
    cursor: '0xf5e0dc'
  normal:
    black:   '0x1e1e2e'
    red:     '0xf28fad'
    green:   '0xabe9b3'
    yellow:  '0xf8bd96'
    blue:    '0x96cdfb'
    magenta: '0xc9cbff'
    cyan:    '0x89dceb'
    white:   '0xd9e0ee'
  bright:
    black:   '0x575268'
    red:     '0xf28fad'
    green:   '0xabe9b3'
    yellow:  '0xf8bd96'
    blue:    '0x96cdfb'
    magenta: '0xc9cbff'
    cyan:    '0x89dceb'
    white:   '0xffffff'

key_bindings:
  - { key: V,        mods: Control|Shift, action: Paste           }
  - { key: C,        mods: Control|Shift, action: Copy            }
  - { key: Key0,     mods: Control,       action: ResetFontSize   }
  - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  - { key: Minus,    mods: Control,       action: DecreaseFontSize }
